# -*- coding: utf-8 -*-
"""Admin Login (TestCases).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OAsUKd8HaO66iUHyu5QpjsCsULKk1kx
"""

import unittest
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class AdminLogin:
    @staticmethod
    def login(email, password):
        if not email or not password:
            raise ValueError("Fields cannot be empty")
        if "'" in password:
            raise ValueError("Security Alert")
        if email != "admin@gv.com":
            raise PermissionError("Unauthorized access")
        if password != "admin123":
            raise ValueError("Invalid admin credentials")
        return "Admin login successful"


class TestAdminLogin(unittest.TestCase):

    def test_TC_A_01_valid_admin_login(self):
        result = AdminLogin.login("admin@gv.com", "admin123")
        self.assertEqual(result, "Admin login successful")
        logger.info("TC-A-01 SUCCESS | Admin login successful")

    def test_TC_A_02_empty_fields(self):
        try:
            AdminLogin.login("", "")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-A-02 FAILURE | %s", e)
            self.fail(e)

    def test_TC_A_03_wrong_password(self):
        try:
            AdminLogin.login("admin@gv.com", "wrong")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-A-03 FAILURE | %s", e)
            self.fail(e)

    def test_TC_A_04_wrong_email(self):
        try:
            AdminLogin.login("wrong@gv.com", "admin123")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-A-04 FAILURE | %s", e)
            self.fail(e)

    def test_TC_A_05_user_credentials(self):
        try:
            AdminLogin.login("user@gv.com", "user123")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-A-05 FAILURE | %s", e)
            self.fail(e)

    def test_TC_A_06_injection(self):
        try:
            AdminLogin.login("admin@gv.com", "'--")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-A-06 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

