# -*- coding: utf-8 -*-
"""Admin Add Game (TestCases).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTlAs46R2G9Rcx7C16mWoaD7IqgUzElE
"""

import unittest
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class GameManager:
    games = []

    @staticmethod
    def add_game(name, price, role):
        if role != "admin":
            raise PermissionError("Unauthorized access")
        if not name:
            raise ValueError("Game name required")
        if price <= 0:
            raise ValueError("Invalid price")
        if name in GameManager.games:
            raise ValueError("Game already exists")
        GameManager.games.append(name)
        return "Game added successfully"


class TestAddGame(unittest.TestCase):

    def test_TC_G_01_valid_game(self):
        result = GameManager.add_game("GTA", 500, "admin")
        self.assertEqual(result, "Game added successfully")
        logger.info("TC-G-01 SUCCESS | Game added")

    def test_TC_G_02_empty_game_name(self):
        try:
            GameManager.add_game("", 500, "admin")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-G-02 FAILURE | %s", e)
            self.fail(e)

    def test_TC_G_03_negative_price(self):
        try:
            GameManager.add_game("FIFA", -500, "admin")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-G-03 FAILURE | %s", e)
            self.fail(e)

    def test_TC_G_04_zero_price(self):
        try:
            GameManager.add_game("PES", 0, "admin")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-G-04 FAILURE | %s", e)
            self.fail(e)

    def test_TC_G_05_duplicate_game(self):
        try:
            GameManager.add_game("GTA", 500, "admin")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-G-05 FAILURE | %s", e)
            self.fail(e)

    def test_TC_G_06_non_admin(self):
        try:
            GameManager.add_game("COD", 500, "user")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-G-06 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

