# -*- coding: utf-8 -*-
"""Admin Game Remove (TestCases).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-RLQfjSdphQ-1QSCZMSylOJ8yUAWdGT
"""

import unittest
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class GameRemoval:
    games = ["GTA"]

    @staticmethod
    def remove(game, role):
        if role != "admin":
            raise PermissionError("Access denied")
        if not game:
            raise ValueError("No game selected")
        if game not in GameRemoval.games:
            raise ValueError("Game not found")
        GameRemoval.games.remove(game)
        return "Game removed successfully"


class TestRemoveGame(unittest.TestCase):

    def test_TC_D_01_valid_removal(self):
        result = GameRemoval.remove("GTA", "admin")
        self.assertEqual(result, "Game removed successfully")
        logger.info("TC-D-01 SUCCESS | Game removed")

    def test_TC_D_02_game_not_exist(self):
        try:
            GameRemoval.remove("XYZ", "admin")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-D-02 FAILURE | %s", e)
            self.fail(e)

    def test_TC_D_03_empty_selection(self):
        try:
            GameRemoval.remove("", "admin")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-D-03 FAILURE | %s", e)
            self.fail(e)

    def test_TC_D_04_user_delete_attempt(self):
        try:
            GameRemoval.remove("GTA", "user")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-D-04 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

