# -*- coding: utf-8 -*-
"""User Login (TestCase).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGAPuHkaSIj10-UeBdglHv8iIlSn7xQJ
"""

import unittest
import re
import logging

# Logging configuration
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class UserLogin:
    @staticmethod
    def login(email, password):
        if not email and not password:
            raise ValueError("Fields cannot be empty")
        if not email:
            raise ValueError("Email required")
        if not password:
            raise ValueError("Password required")
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise ValueError("Invalid email format")
        if "'" in email or "'" in password:
            raise ValueError("Security Alert: Injection detected")
        if email != "user@gv.com" or password != "user123":
            raise ValueError("Invalid credentials")
        return "Login successful"


class TestUserLogin(unittest.TestCase):

    # TC-L-01 (ONLY SUCCESS CASE)
    def test_TC_L_01_valid_login(self):
        result = UserLogin.login("user@gv.com", "user123")
        self.assertEqual(result, "Login successful")
        logger.info("TC-L-01 SUCCESS | Login successful")

    # TC-L-02
    def test_TC_L_02_empty_fields(self):
        try:
            UserLogin.login("", "")
            self.fail("TC-L-02 FAILED | Error expected but login succeeded")
        except Exception as e:
            logger.error("TC-L-02 FAILURE | %s", e)
            self.fail(e)

    # TC-L-03
    def test_TC_L_03_empty_password(self):
        try:
            UserLogin.login("user@gv.com", "")
            self.fail("TC-L-03 FAILED | Error expected but login succeeded")
        except Exception as e:
            logger.error("TC-L-03 FAILURE | %s", e)
            self.fail(e)

    # TC-L-04
    def test_TC_L_04_empty_email(self):
        try:
            UserLogin.login("", "user123")
            self.fail("TC-L-04 FAILED | Error expected but login succeeded")
        except Exception as e:
            logger.error("TC-L-04 FAILURE | %s", e)
            self.fail(e)

    # TC-L-05
    def test_TC_L_05_invalid_email(self):
        try:
            UserLogin.login("wrong@gv.com", "user123")
            self.fail("TC-L-05 FAILED | Error expected but login succeeded")
        except Exception as e:
            logger.error("TC-L-05 FAILURE | %s", e)
            self.fail(e)

    # TC-L-06
    def test_TC_L_06_invalid_password(self):
        try:
            UserLogin.login("user@gv.com", "wrong123")
            self.fail("TC-L-06 FAILED | Error expected but login succeeded")
        except Exception as e:
            logger.error("TC-L-06 FAILURE | %s", e)
            self.fail(e)

    # TC-L-07
    def test_TC_L_07_invalid_email_format(self):
        try:
            UserLogin.login("usergv.com", "user123")
            self.fail("TC-L-07 FAILED | Error expected but login succeeded")
        except Exception as e:
            logger.error("TC-L-07 FAILURE | %s", e)
            self.fail(e)

    # TC-L-08
    def test_TC_L_08_sql_injection(self):
        try:
            UserLogin.login("' OR 1=1", "test")
            self.fail("TC-L-08 FAILED | Security error expected")
        except Exception as e:
            logger.error("TC-L-08 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

