# -*- coding: utf-8 -*-
"""User Add to Cart (TestCases).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvKmMJsuVkx9d-X52J1sYqVMQhSelJr8
"""

import unittest
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class Cart:
    cart = []

    @staticmethod
    def add(game, logged_in):
        if not logged_in:
            raise PermissionError("Login required")
        if not game:
            raise ValueError("Game not found")
        if game in Cart.cart:
            raise ValueError("Already in cart")
        Cart.cart.append(game)
        return "Game added to cart"


class TestCart(unittest.TestCase):

    def test_TC_C_01_valid_add(self):
        result = Cart.add("GTA", True)
        self.assertEqual(result, "Game added to cart")
        logger.info("TC-C-01 SUCCESS | Game added to cart")

    def test_TC_C_02_duplicate_game(self):
        try:
            Cart.add("GTA", True)
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-C-02 FAILURE | %s", e)
            self.fail(e)

    def test_TC_C_03_invalid_game(self):
        try:
            Cart.add("", True)
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-C-03 FAILURE | %s", e)
            self.fail(e)

    def test_TC_C_04_not_logged_in(self):
        try:
            Cart.add("COD", False)
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-C-04 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

