# -*- coding: utf-8 -*-
"""User Registration (TestCases).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwGDGZADF-dHLV0BJaVBV1C2hJfitt--
"""

import unittest
import re
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class UserRegistration:
    existing_emails = ["user@gv.com"]

    @staticmethod
    def register(username, email, password, confirm):
        if not username or not email or not password or not confirm:
            raise ValueError("All fields required")
        if not re.match(r"^[a-zA-Z0-9_]+$", username):
            raise ValueError("Invalid username")
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise ValueError("Invalid email")
        if password != confirm:
            raise ValueError("Password mismatch")
        if len(password) < 6:
            raise ValueError("Password too weak")
        if email in UserRegistration.existing_emails:
            raise ValueError("Email already exists")
        return "Registration successful"


class TestUserRegistration(unittest.TestCase):

    def test_TC_R_01_valid_registration(self):
        result = UserRegistration.register(
            "newuser", "new@gv.com", "strong123", "strong123"
        )
        self.assertEqual(result, "Registration successful")
        logger.info("TC-R-01 SUCCESS | Registration successful")

    def test_TC_R_02_empty_form(self):
        try:
            UserRegistration.register("", "", "", "")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-R-02 FAILURE | %s", e)
            self.fail(e)

    def test_TC_R_03_invalid_email(self):
        try:
            UserRegistration.register("user", "usergv.com", "pass123", "pass123")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-R-03 FAILURE | %s", e)
            self.fail(e)

    def test_TC_R_04_password_mismatch(self):
        try:
            UserRegistration.register("user", "u@gv.com", "pass123", "pass")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-R-04 FAILURE | %s", e)
            self.fail(e)

    def test_TC_R_05_weak_password(self):
        try:
            UserRegistration.register("user", "u@gv.com", "123", "123")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-R-05 FAILURE | %s", e)
            self.fail(e)

    def test_TC_R_06_duplicate_email(self):
        try:
            UserRegistration.register("user", "user@gv.com", "pass123", "pass123")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-R-06 FAILURE | %s", e)
            self.fail(e)

    def test_TC_R_07_invalid_username(self):
        try:
            UserRegistration.register("@@@", "u@gv.com", "pass123", "pass123")
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-R-07 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

