# -*- coding: utf-8 -*-
"""User Wishlist (TestCases).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duun3qbEWbTP1wMmNLR5Vi3m0uvgHaKh
"""

import unittest
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)


class Wishlist:
    wishlist = []

    @staticmethod
    def add(game, logged_in):
        if not logged_in:
            raise PermissionError("Login required")
        if not game:
            raise ValueError("Game not found")
        if game in Wishlist.wishlist:
            raise ValueError("Already wishlisted")
        Wishlist.wishlist.append(game)
        return "Added to wishlist"


class TestWishlist(unittest.TestCase):

    def test_TC_W_01_valid_wishlist(self):
        result = Wishlist.add("GTA", True)
        self.assertEqual(result, "Added to wishlist")
        logger.info("TC-W-01 SUCCESS | Added to wishlist")

    def test_TC_W_02_duplicate_wishlist(self):
        try:
            Wishlist.add("GTA", True)
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-W-02 FAILURE | %s", e)
            self.fail(e)

    def test_TC_W_03_invalid_game(self):
        try:
            Wishlist.add("", True)
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-W-03 FAILURE | %s", e)
            self.fail(e)

    def test_TC_W_04_not_logged_in(self):
        try:
            Wishlist.add("COD", False)
            self.fail("Error expected")
        except Exception as e:
            logger.error("TC-W-04 FAILURE | %s", e)
            self.fail(e)


unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

